### ISSUE TITLE
Doesn't work on Windows 10 + Android Studio

### ISSUE THREAD

**Issue by metavaults** [aryaminus/RN-firechat#1]
The problem occurs, whenever I execute 'npm install' command:

![image](https://user-images.githubusercontent.com/13028072/38432444-bc86a522-39c7-11e8-8582-8d2b40e71504.png)

Using Windows 10
DIdn't change any packages (master branch)

**Comment by aryaminus** [comment]
Shows some warning with `react-navigation` of tab-view for listing of friends.
I'll look into it as react-navigation has gone through some upgrades. Does `npm i` result to nothing as it's just a warning?
