### ISSUE TITLE
Large number of anonymous user creation in firebase 

### ISSUE THREAD

**Issue by Muthuvel2019** [aryaminus/RN-firechat#4]
When I am running this app, it is lot of anonymous users creation happening. 
What could be the reason ?

**Comment by SaiKiran322** [comment]
@Vahai  can you show the firebase code?

**Comment by Muthuvel2019** [comment]
I have not changed anything for firebase code. I have cloned from master branch. and put my google-services.json.

**Comment by Muthuvel2019** [comment]
![Screenshot 2019-03-11 at 3 40 49 PM](https://user-images.githubusercontent.com/13657026/54116163-2d351900-4414-11e9-9d21-435f73e278fa.png)

Please find it there are 475 anonymous users created.

**Comment by aryaminus** [comment]
[
<img width="1189" alt="Screen Shot 2019-03-11 at 6 52 36 PM" src="https://user-images.githubusercontent.com/16350823/54126125-ed2f5f80-442e-11e9-8816-e5007c73d7bf.png">
](url)

GloChat uses anon user. Solution: don't do [signInAnonymously](https://github.com/aryaminus/RN-firechat/blob/master/app/components/Backend.js#L13) instead use the auth credentials used when logging in.

**Comment by Muthuvel2019** [comment]
Already logged in. Why it has to be logged in again in Backend.js also. 
I have changed like as below, in Backend.js
  constructor() {
//    firebase.auth().onAuthStateChanged(user => {
//      if (user) {
//        this.setUid(user.uid);
//      } else {
//        firebase
//          .auth()
//          .signInAnonymously()
//          .catch(error => {
//            alert(error.message);
//          });
//      }
//    });
  if (firebase.auth().currentUser) {
     this.setUid(firebase.auth().currentUser.uid);
    }
  else {
    alert("Please Login....");
  }
  }

If you are authenticating in else part, it will call the onAuthStateChanged again. That is why lot of anonymous user created I suppose.  does it make sense ?

**Comment by aryaminus** [comment]
You are on the track. As you see this repo is a boilerplate for basic firebase usage and as I'm asking for a new username and then passing into GloChat, had to sign-in anon. Just change the passed prop to fetch the default username from firebase.
